spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: 02468
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
server:
    port: 8080
    servlet:
        context-path: /sbank
        session:
          timeout:30m